### ISSUE TITLE
Refactor code using React hooks.

### ISSUE THREAD

**Issue by simplegoose** [simplegoose/math-magicians#4]
This project has been created using the React UI library. These are some of the features of React library that have been used:

- Functional components have been used instead of class components.
- The hook `useState` has been used rather than using `this.setState` when using class components.
- `props` destructuring has been used to get props by their names.
- Lifting state up has been used on the `Button` functional component.

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @simplegoose 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
